### ISSUE TITLE
Purchase date is not correct in the json files

### ISSUE THREAD

**Issue by bergje4** [audiamus/BookLibConnect#146]
The "purchase_date" field in the json files (export directory) is displaying "0001-01-01T00:00:00" instead of the actual date the item was purchased. Would it be possible to put the actual purchase date in that field?

Thanks for a great piece of software!

**Comment by audiamus** [comment]
The purpose of the export json files is to provide compatibility for AAX Audio Converter which expects the output from the retired Audible Win10 app. 

I had to look this up in the source code: To keep it simple I reuse one of the json data structures from the Audible server API. And that happens to have this purchase-date field. I don't fill it it for export, because, apparently, it's not needed. The meta data embedded in the audio files also has the this entry and AAX Audio Converter takes the purchase date from there. I could make this field nullable for json and then it would no longer confuse any reader. I'll put it on the to-do list.
