### ISSUE TITLE
The books are in the library but I can't download them

### ISSUE THREAD

**Issue by GRARTEL** [audiamus/BookLibConnect#169]
When I click on the Download button in the list I get the following icon.

![image](https://github.com/user-attachments/assets/2790f129-8222-475a-984c-7095c6fedea8)

But from the application I can listen to it

**Comment by audiamus** [comment]
The log file may tell us more.

**Comment by GRARTEL** [comment]
[BookLibConnect_2024-10-15_002.log](https://github.com/user-attachments/files/17381770/BookLibConnect_2024-10-15_002.log)
 This is the log file when I'm going to download those files.
It comes out as if I didn't have permission but when I enter the website I can hear them.

**Comment by audiamus** [comment]
The log file lists an exception, but I don't know whether that causes the problem or is caused by the problem.
In the `C:\Users\<user>\AppData\Local\audiamus\BookLibConnect\tmp` folder there should be a file
`LicenseResponse_B09NDDDZ89-2024_10_15-11_27_49.json` (one of the download attempts). Can you upload that as well?

**Comment by GRARTEL** [comment]
[LicenseResponse_B09NDDDZ89-2024_10_15-11_27_49.json](https://github.com/user-attachments/files/17384456/LicenseResponse_B09NDDDZ89-2024_10_15-11_27_49.json)
This is the file

**Comment by audiamus** [comment]
Audible says in this json file that the licence has been denied, giving four explicit reasons.
