### ISSUE TITLE
New book not showing up, Empty book list after recreating profile

### ISSUE THREAD

**Issue by Googlhupf** [audiamus/BookLibConnect#175]
I bought a new book on 2024-11-18 and it didn't show up as usual. My previous purchases were still in the list, even after a full resync.

The newly bought book did show up in the LibraryResponse json

After deleting my old profile and creating a new profile, the list is completely empty.

I was able to convert a book bought on 2024-11-14 on the same day successfully.

Maybe Amazon changed something? Different server response maybe?

Fantastic program, BTW. 😁

**Comment by MTPlanet** [comment]
I was missing a single book. My lastest purchase. Resync nothing. Completely uninstalled and reinstalled after seeing you post. I was able to get my list to load but still missing last purchase. After careful review of the settings. I failed to check "adult products" Not really what I would call "adult" but after doing this I now have my complete list. Including a book on human sexuality. Somehow that is an adult product, where many other titles could be seen as "adult". Hope this helps someone. Good luck.

**Comment by Googlhupf** [comment]
Adult is checked here. List is staying empty. Did you delete your BookLibConnect data from %localappdata%\BookLibConnect before reinstalling?

**Comment by MTPlanet** [comment]
uninstalled then verified C:\Users\UESR_NAME\AppData\Local\audiamus\BookLibConnect was deleted. Went to Amazon and deleted all devices except true devices, my phone, iPad and such. Made sure C:\Program Files\audiamus no longer had 'Book Lib Connect" folder. Installed and was prompted to create the account like the first time. Then all books loaded except the one due to the one due to "adult products" not being checked.

**Comment by Googlhupf** [comment]
OK. Seems like I have to eat my own words here. After deleting %localappdata%\BookLibConnect and recreating all profiles, everything seems to be working as it should. My bad. *facepalm* Case closed
