### ISSUE TITLE
Library empty when trying to download

### ISSUE THREAD

**Issue by Bhaeron** [audiamus/BookLibConnect#18]
After setting up a new profile and clicking "Download" the library windows is empty, although there should be several audiobooks to dowload. This problem only exists for one specific profile. Others seem to be working with no problem.

**Comment by audiamus** [comment]
There are a few unknowns here, as I myself have only one profile to play with and some of the multi-profile stuff is a bit difficult to verify.

> This problem only exists for one specific profile. Others seem to be working with no problem.

1. Does this mean you have at least 3 profiles set up and at least 2 are showing the books you expect?

2. The profile that does not show any books, are this books that may also exist under one of the other profiles? Those would be ignored if the ASIN of such a book is already registered in the local database, but for a different profile.

3. If those books are unique across all profiles, did the server reply with a list of books or has that been empty as well? The server response can be found in `C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect\tmp`, as `LibraryResponse-*.json`.

4. If that json file is more or less empty, did you purchase books in another profile more recently than the missing ones? It could be a bug with the latest purchase timestamp here. Normally Book Lib Connect will only ask the server for additions to your library since your last purchase (the next version will allow a full resync). And this last purchase timestamp may not be filtered by profile at the moment, which would be wrong. 

5. If that json file is not empty and has the entries you'd expect: The missing titles are books, not podcasts? Podcasts are currently ignored, as they have to be downloaded differently, and I still have to find out how. And if the missing books could be adult titles, did you check the adult filter?

**Comment by Bhaeron** [comment]
Apologies for the late reply:

1. That is correct.
2. No, the books in question are unique to this specific profile.
3. The server response for that profile seems to be empty. I could only find entries that point to other profiles while browsing the files.
4. No, the books in question have been purchased in the past and should not conflict with recent purchases from other profiles.
5. The missing titles are in fact books, yes. And no, they are no adult titles.

Thank you very much for your time. All the best.

**Comment by audiamus** [comment]
> The server response for that profile seems to be empty. I could only find entries that point to other profiles while browsing the files.

Thank you very much. I think I've found it. As I suspected, the server query for the latest additions to the library wasn't profile specific. So, if you made purchases in another profile later than on the one affected, the older books for that profile would not show up.

I have fixed this in version 0.4, released just now. I also added a full resynchronization option which is independent of purchase date.
