### ISSUE TITLE
Hide refunded books

### ISSUE THREAD

**Issue by Pegoth** [audiamus/BookLibConnect#57]
I refunded some books and now they are always on the top of the Library with crossed web icon.

Is it possible to hide them? Are they just bugged out?

Image of the library:
![image](https://user-images.githubusercontent.com/20708012/178302385-341feca8-1908-497e-a169-eb903e2239ef.png)

**Comment by dreiundzwanziguhrvierzig** [comment]
![image](https://user-images.githubusercontent.com/61885248/178315804-4e952dd2-9a47-4047-ae9b-316e68fc79de.png)

Since a few days (at release 0.8 and still at 0.9) the tool shows me 95% of my tracks as locked. There are no returned/refunded ones among them.

Also the new free subscription titles are partly locked and partly not to find at all. Although I was able to download some that are now gone or blocked.

Do I need to clear a cache or reload something? Or did Audible come up with something rude?

**Comment by audiamus** [comment]
No, I don't think we have such an option yet. I will put it on the to-do list. 
But, at least for now, detection of books no longer in your library is working as intended.
